Add missing <exception> include
https://reviews.llvm.org/D146097 removed the transitive include for
<exception>, which caused the following issue:

In file included from ../../third_party/spirv-cross/spirv_common.hpp:28:
../../third_party/spirv-cross/spirv_cross_containers.hpp:334:9: error:
no member named 'terminate' in namespace 'std

This patch adds the missing include to fix the issue.